version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-entrevista
    restart: always
    environment:
      MYSQL_DATABASE: entrevista
      MYSQL_USER: entrevista_user
      MYSQL_PASSWORD: entrevista_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
